### ISSUE TITLE
Old InRelease file left

### ISSUE THREAD

**Issue by pboguslawski** [apt-mirror/apt-mirror#45]
Hi,,

We've noticed that  there is no InRelease file for Debian 8.2 in

ftp://ftp.se.debian.org/debian/dists/jessie/

but there was such file for Debian 8.1 in this dir and apt-mirror seems to skip cleaning InRelease files; skipping code in apt-mirror (*):

foreach ( keys %urls_to_download )
{
    s[^(\w+)://][];
    s[~][%7E]g if get_variable("_tilde");
    $skipclean{$_} = 1;
    $skipclean{$_} = 1 if s[\.gz$][];
    $skipclean{$_} = 1 if s[\.bz2$][];
    $skipclean{$_} = 1 if s[\.xz$][];
}

The result of mirroring

ftp://ftp.se.debian.org/debian/dists/jessie/

with apt-mirror has now old InRelease (left from Debian 8.1) and new Release and Release.gpg (from Debian 8.2) which generates apt-get Hash Sum errors because apt-get seems to process InRelease if found, not Release+Release.gpg.

Also, the code (*) seems to have a bug: line with "$skipclean{$_} = 1;" already marks all the files from urls_to_download probably and lines

    $skipclean{$_} = 1 if s[\.gz$][];
    $skipclean{$_} = 1 if s[\.bz2$][];
    $skipclean{$_} = 1 if s[\.xz$][];

do nothing (maybe the intention was to set it to 0 there to allow cleaning compressed stuff if compression format changes)?

What is the whole urls_to_download cleaning skipping for? What if repo maintainers change compression format from bz2 to xz or switch from InRelease to Release+Release.gpg only or from Release+Release.gpg  to InRelease only?

Is it a problem to remove whole (*) code and let apt-mirror to sync all files from urls_to_download 1:1 without leaving old stuff there?

Regards,
Pawel

**Comment by pboguslawski** [comment]
I see that

   $skipclean{$_} = 1 if s[\.gz$][];
   $skipclean{$_} = 1 if s[\.bz2$][];
   $skipclean{$_} = 1 if s[\.xz$][];

is required to protect also uncompressed file version.

Not all repos has debian-installer component so consider this mod:

--- apt-mirror.orig.master	2015-09-09 19:23:06.000000000 +0200
+++ apt-mirror	2015-09-09 21:13:25.359932307 +0200
@@ -672,6 +672,12 @@
     local $/ = "\n\n";
     $mirror = get_variable("mirror_path") . "/" . $path;
 
+    if (! -f "$path/$index")
+    {
+        warn("apt-mirror: index file $path/$index does not exit") unless $index =~ /debian-installer/;
+        return;
+    }
+
     if ( $index =~ s/\.gz$// )
     {
         system("gunzip < $path/$index.gz > $path/$index");

Regards,
Pawel

**Comment by Hellnino18** [comment]
Hi Pawel,

I'm not sure to undestand what you're describing upper, but I have a problem with my apt-mirror since we are in Debian 8.2. I have a lot of Sum Hash Mismatch and I think it's for the same problem.

Could you be more explicit plz? Your workaround is not very well presented.

I think for the moment we can edit the postmirror.sh and put this line :  

find "REMOTE_MIRROR/debian/dists/jessie" -name "InRelease" -exec rm {} \;

Regards,

**Comment by pboguslawski** [comment]
Hi,

Debian 8.2 does not contain InRelease file in ftp://ftp.debian.org/debian/dists/jessie/ and InRelease was present in this dir in Debian 8.1.

apt-mirror does not handle such update and leaves InRelease untouched in copy which gives us copy with fresh Release+Release.gpg files and old InRelease from Debian 8.1. apt-get tries InRelease if found and sum mismatches occur.

We've resolved this issue by removing manually all InRelease files from apt-mirror "mirror" and "skel directories" (cmd to find like "find mirror -name InRelease") and forcing apt-mirror to sync (which downloaded only fresh files and resolved issue).

Remember about backup before applying such changes :)

I think apt-mirror should better handle such quirks and leave mirror 1:1 after successfull sync, removing old files.

BTW: we've send question to Debian FTP Mirror team about lack of InRelease in Debian 8.2 - no answer till now.

Regards,
Pawel

**Comment by Hellnino18** [comment]
I have always the problem with the jessie backports. The InRelease file exists on the repository http://ftp.fr.debian.org/debian/dists/jessie-backports/

The only way to avoid the Sum Mismatch is to delete Packages.bz2. I don't understand why.

Regars,

Nath

**Comment by Kunzol** [comment]
@Hellnino18, as far as I can see, if you delete the "Packages.bz2", the OLD inRelease file is used by "apt-get update" and you will not see newer updates. Better to delete the old "InRelease", which lets "apt-get update" use the NEW "Packages.*" file as the index.

@ALL: Besides this I experiance something else. I deleted the old "InRelese" file from the mirror directory, but every day, it came back, even if it was not available anymore in the repo I mirror (404 on the InRelease). 

After some search in the source and filesystem, I realized that the OLD "InRelease" file is still in the "skel_path" directory and is copied in the mirror, every time "apt-mirror" is run. 

Thus the patch in the "clean" function might not be the perfect solution, because it does not handle the files in the cache of the index files in "skel_path". The clean works only on the "mirror_path".

Some cleanup of the index files is needed, too.  

I see, that it is optimal to cache index files and only download newer files. But "cache" means also to cleanup removed cache items.

I will check if I can provide a fix, but maybe someone who is "in the code" could do it much easier.

**Comment by pashinin** [comment]
My case for Ubuntu: apt-mirror tries to download `InRelease` file which does not exist anymore.
This causes error at a desktop which tries to `apt-get update`

```
sudo apt-get update
Get:1 http://apt.....com vivid InRelease [269 B]
99% [1 InRelease gpgv 269 B] [Waiting for headers]Splitting up /var/lib/apt/lists/partial/apt....com_mirror.yIgn http://apt.....com vivid InRelease       d signature failed
E: GPG error: http://apt.....com vivid InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
```

**Comment by ljoets** [comment]
Hi,
I have no InRelease file on my mirror.
"# find /depot -name InRelease" returns noting.

BTW, I have hash problems on clients with
ftp.fr.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages
ftp.fr.debian.org/debian/dists/jessie-backports/main/binary-i386/Packages

I noticed that http://ftp.fr.debian.org/debian/dists/jessie-backports/InRelease exists, but seems not to be downloaded by apt-mirror :
# ls /depot/mirror/ftp.fr.debian.org/debian/dists/jessie-backports
contrib  main  non-free  Release  Release.gpg

**Comment by Kunzol** [comment]
As I said. It is not in the "mirror_path" it is in the "skel_path" (index cache).

The the index cache (skel_path) is not cleaned up correctly.
Just delete all files in the index cache (skel_path) from time to time (or whenever a problem occurs).

**Comment by ljoets** [comment]
I did it.
That has not solved the problem :-(

**Comment by Diamond2** [comment]
I had the same issue here. I cleaned skel_path and it fixed the issue as Kunzol said.

**Comment by andreazorzetto** [comment]
Very similar is happening to me too with another repository that I'm mirroring on 4 ubuntu boxes
https://packagecloud.io/grafana/stable/debian

I had to remove the skel folder for that repo in order to get the latest Grafana version released
That's quite annoying and I'm not sure how much I can rely on this solution

**Comment by madscientist159** [comment]
Just got hit by this after Debian Stretch went from testing to stable.  Any chance of a "proper" fix or is the deletion of the skel directory the official fix method after release?

**Comment by chani** [comment]
Hi,

i regularly run into this issue. Is there some fix for this available? Some script which would delete the outdated InRelease file?

**Comment by fbarbeira** [comment]
This bug hits again with Debian buster release

**Comment by chutzimir** [comment]
This was fixed with #156. Can be closed.

**Comment by nE0sIghT** [comment]
> This was fixed with https://github.com/apt-mirror/apt-mirror/pull/156. Can be closed.

This issue still not fixed. The main problem is that apt-mirror doesn't clean skel folder so outdated index files are used in metadata parsing stage
